force-app/main/default/objects/Channel__mdt/Channel__mdt.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <pluralLabel>Channels</pluralLabel>
</CustomObject>

force-app/main/default/objects/ChannelHandler__mdt/ChannelHandler__mdt.object-meta.xml
<CustomObject>
    <label>Channel Handler</label>
    <pluralLabel>Channels Handlers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Subscriber__mdt/Subscriber__mdt.object-meta.xml
<CustomObject>
    <label>Subscriber</label>
    <pluralLabel>Subscribers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Subscription__mdt/Subscription__mdt.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <pluralLabel>Subscriptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Subscription__mdt/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <referenceTo>Channel__mdt</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Subscription__mdt/fields/ChannelHandlerClassName__c.field-meta.xml
<CustomField>
    <fullName>ChannelHandlerClassName__c</fullName>
    <label>Channel Handler</label>
    <referenceTo>ChannelHandler__mdt</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Subscription__mdt/fields/ExecutionOrder__c.field-meta.xml
<CustomField>
    <fullName>ExecutionOrder__c</fullName>
    <label>Execution order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscription__mdt/fields/Subscriber__c.field-meta.xml
<CustomField>
    <fullName>Subscriber__c</fullName>
    <label>Subscriber</label>
    <referenceTo>Subscriber__mdt</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/SubscriptionsSelector.cls
public with sharing class SubscriptionsSelector {
    public static SubscriptionsSelector Instance {
        get {
            if (Instance == null) {
                Instance = new SubscriptionsSelector();
            }

            return Instance;
        }
        private set;
    }

    public List<Subscription__mdt> selectByChannelAndSubscribers(String channel, Set<String> subscribersName) {
        System.debug('channel: ' + channel);
        System.debug('subscribersName: ' + subscribersName);
        return [
            SELECT Id, Channel__r.DeveloperName, ChannelHandlerClassName__r.DeveloperName, Subscriber__r.DeveloperName
            FROM Subscription__mdt
            WHERE Channel__r.DeveloperName = :channel AND Subscriber__r.DeveloperName IN :subscribersName AND Active__c = TRUE
            ORDER BY Subscriber__c, Channel__c, ExecutionOrder__c ASC
        ];
    }
}